In [25]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr2 = np.array(6)
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr)
print(type(arr))
print("")

print(arr2)
print(type(arr2))
print("")

print(arr3)
print(type(arr3))
print("")

print(arr4)
print(type(arr4))
print("")

[1 2 3 4 5]
<class 'numpy.ndarray'>

6
<class 'numpy.ndarray'>

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>



In [38]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr2 = np.array(6)
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([ [[1,2,3],[4,5,6]] , [[7,8,9],[10,11,12]] ])

print(arr2.ndim)
print(arr.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
1
2
3


In [42]:
import numpy as np

arr = np.array([ [[1,2,5],[4,1,6]] , [[7,8,9],[10,10,12]] ])

num = int(input("enter"))

for i in range(2) :
    for j in range(2) :
        for k in range(3) :
            if arr[i,j,k] == num :
                print("index" , i , j , k )
                print('')
                
                

enter 10


index 1 1 0

index 1 1 1



In [53]:
import numpy as np

arr = np.array([10,4,6,2,7,3,8])

arr.sort()
for i in range(len(arr)):
    if arr[i]>=4:
        print(arr[i:])
        print(arr[:i])
        break

[ 4  6  7  8 10]
[2 3]


In [66]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[-3:-1])
print(arr[::3])

[5 6]
[1 4 7]
